[theme]
borderColor = "#65737e" #medium grey, color of seperation–line between KPIs and Plots
primaryColor = "#153b5c" #color for sidebar buttons 
backgroundColor = "#FFFCF2" #background color of main page
secondaryBackgroundColor = "#e8dcc8"
textColor = "153b5c" 
secondarytextColor = "77797D"
dataframeHeaderBackgroundColor = "#E3E3E3"
dataframeBorderColor = "77797D"
showSidebarBorder = true
showWidgetBorder = true



[theme.sidebar]
secondaryBackgroundColor = "#B3E2FF"
backgroundColor = "#DED9D3"
